### ISSUE TITLE
Unable to create rule for blocking AAAA query-type

### ISSUE THREAD

**Issue by viready** [oskar456/xt_dns#1]
Hi,

I installed the package successfully on RHEL 6.3 x86_64 machine.
When trying to create a rule to block AAAA type DNS query, I get the following message:
_No chain/target/match by that name._

Here's what I tried to do:

> [root@localhost XT-WORKS]# iptables -N AAAA
> [root@localhost XT-WORKS]# iptables -A INPUT -p udp --dport 53 -j AAAA
> [root@localhost XT-WORKS]# iptables -A AAAA -m dns --query-type AAAA -j DROP
> iptables: No chain/target/match by that name.
> [root@localhost XT-WORKS]# iptables -A AAAA -m dns --query-type AAAA -j ACCEPT
> iptables: No chain/target/match by that name.

I am following the examples written here: http://software.klolik.org/xt_dns/#example
I'd love to see this thing work on my machine. Could someone help me pointing out what I'm doing wrong?
Thanks.

**Comment by msvijai** [comment]
I have inserted the xt_dns.ko & also copied libxt_dns.so to the path /lib/xtables/ but still I am getting the below error. Can you please let me know what am I missing.
#iptables -m dns --help
iptables v1.4.14: Couldn't load match `dns':No such file or directory
Try `iptables -h' or 'iptables --help' for more information.

>>uname -a
Linux debian 3.2.0-4-amd64 #1 SMP Debian 3.2.68-1+deb7u3 x86_64 GNU/Linux

>>iptables v1.4.14
