### ISSUE TITLE
xt_dns module - iptables couldn't load match dns error

### ISSUE THREAD

**Issue by msvijai** [oskar456/xt_dns#4]
I have inserted the xt_dns.ko & also copied libxt_dns.so to the path /lib/xtables/ but still I am getting the below error. Can you please let me know what am I missing.
# iptables -m dns --help

iptables v1.4.14: Couldn't load match dns':No such file or directory
Try iptables -h' or 'iptables --help' for more information.
# uname -a

Linux debian 3.2.0-4-amd64 #1 SMP Debian 3.2.68-1+deb7u3 x86_64 GNU/Linux

iptables v1.4.14

**Comment by oskar456** [comment]
Sorry for not noticing this. I hope you've already found a solution or workaround.
