### ISSUE TITLE
iptables: No chain/target/match by that name.

### ISSUE THREAD

**Issue by takenek** [oskar456/xt_dns#5]
Hello Ondřej,
I don`t know You still support Your project but i got problem on new machine i saw this problem was exist in old machines but this i got on new one ofc i use the newlatest version of Your module:
I want to DROP all AAAA queries from 1.1.1.1 ip address.
root # /sbin/iptables --insert INPUT -s 1.1.1.1 -p udp --dport 53 -m dns --dns-query --query-type AAAA -j DROP
iptables: No chain/target/match by that name.

I use Debian 7.10:
root# iptables -V
iptables v1.4.14
root# uname -a
Linux DNS-TEST 3.2.0-4-amd64 #1 SMP Debian 3.2.78-1 x86_64 GNU/Linux

Best Regards
Marek

**Comment by oskar456** [comment]
Hello Marek,

I cannot reproduce your issue. I just installed a fresh Debian 7, installed necessary dependecies, compiled xt_dns and tried your command:

    # apt-get install git build-essential linux-headers-amd64 iptables-dev
    # git clone https://github.com/oskar456/xt_dns.git
    # cd xt_dns
    # make
    # make install
    # /sbin/iptables --insert INPUT -s 1.1.1.1 -p udp --dport 53 -m dns --dns-query --query-type AAAA -j DROP
    # iptables -L -v
    Chain INPUT (policy ACCEPT 26 packets, 1832 bytes)
     pkts bytes target     prot opt in     out     source               destination         
        0     0 DROP       udp  --  any    any     1.1.1.1              anywhere             udp dpt:domain dns query qtype AAAA
    # iptables -V
    iptables v1.4.14
    # uname -a
    Linux cloud255-220 3.2.0-4-amd64 #1 SMP Debian 3.2.78-1 x86_64 GNU/Linux

Make sure your kernel module is compiled properly and can be inserted. Also make sure the file `/lib/xtables/libxt_dns.so` is installed properly. You can check whether the iptables utility sees the module by issuing `iptables -m dns --help`.

Feel free to reopen in case you find something new.
